version: '2'
plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          min_tokens: 20
        javascript:
          min_tokens: 20
        dart:
          min_tokens: 20

